JEVEGA_UsDiagnosticClinic/Controllers/PatientDataController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JEVEGA_UsDiagnosticClinic;

namespace JEVEGA_UsDiagnosticClinic.Controllers
{
    [Authorize]
    public class PatientDataController : Controller
    {
        private JEVEGA_USEntities db = new JEVEGA_USEntities();
        public static string patient_id_number = "";

        [Authorize]
        // GET: PatientData
        public ActionResult Index()
        {
            string usertype = Session["USER_TYPE"].ToString();
            if (usertype == "1")   //-- Admin user ... 
            {
                return View(db.PatientDatas.ToList());
            }
            else { return RedirectToAction("UnauthorizedAccess", "Users"); }

        } //--

        // GET: PatientData/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PatientData patientData = db.PatientDatas.Find(id);
            if (patientData == null)
            {
                return HttpNotFound();
            }

            ViewBag.MaritalStatusList = new SelectList(db.MaritalStatus, "StatusCode", "Status");
            List<SelectListItem> genderList = new List<SelectListItem>();
            SelectListItem item1 = new SelectListItem { Text = "Male", Value = "M" };
            genderList.Add(item1);
            SelectListItem item2 = new SelectListItem { Text = "Female", Value = "F" };
            genderList.Add(item2);
            ViewBag.GenderList = genderList;

            return View(patientData);
        }

        // GET: PatientData/Create
        public ActionResult Create()
        {
            ViewBag.MaritalStatusList = new SelectList(db.MaritalStatus, "StatusCode", "Status");

            List<SelectListItem> genderList = new List<SelectListItem>();
            SelectListItem item1 = new SelectListItem { Text = "Male", Value = "M" };
            genderList.Add(item1);
            SelectListItem item2 = new SelectListItem { Text = "Female", Value = "F" };
            genderList.Add(item2);
            ViewBag.GenderList = genderList;

            return View();
        }

        // POST: PatientData/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Patient_Id,Lastname,Firstname,Age,Sex,Address,Email,Phone,Status,LMP")] PatientData patientData)
        {
            string patientId = patientData.Patient_Id;
            bool patientIdExist = checkPatientExamIdExist(patientId);

            if (ModelState.IsValid && !patientIdExist)
            {
                db.PatientDatas.Add(patientData);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                if (patientIdExist)
                {
                    ViewBag.ErrorDuplicatePatientId = "Patient  Id No. " + patientId + " already existed!  Please enter a different Id number.";
                }

                ViewBag.MaritalStatusList = new SelectList(db.MaritalStatus, "StatusCode", "Status");

                List<SelectListItem> genderList = new List<SelectListItem>();
                SelectListItem item1 = new SelectListItem { Text = "Male", Value = "M" };
                genderList.Add(item1);
                SelectListItem item2 = new SelectListItem { Text = "Female", Value = "F" };
                genderList.Add(item2);
                ViewBag.GenderList = genderList;
            }

            return View(patientData);
        }

        // GET: PatientData/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PatientData patientData = db.PatientDatas.Find(id);
            if (patientData == null)
            {
                return HttpNotFound();
            }

            ViewBag.MaritalStatusList = new SelectList(db.MaritalStatus, "StatusCode", "Status");
            List<SelectListItem> genderList = new List<SelectListItem>();
            SelectListItem item1 = new SelectListItem { Text = "Male", Value = "M" };
            genderList.Add(item1);
            SelectListItem item2 = new SelectListItem { Text = "Female", Value = "F" };
            genderList.Add(item2);
            ViewBag.GenderList = genderList;

            patient_id_number = patientData.Patient_Id.ToString();
            return View(patientData);
        }

        // POST: PatientData/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Patient_Id,Lastname,Firstname,Age,Sex,Address,Email,Phone,LoginPassword,Status,LMP")] PatientData patientData)
        {
            patientData.Patient_Id = patient_id_number;

            if (ModelState.IsValid)
            {
                db.Entry(patientData).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.MaritalStatusList = new SelectList(db.MaritalStatus, "StatusCode", "Status");
                List<SelectListItem> genderList = new List<SelectListItem>();
                SelectListItem item1 = new SelectListItem { Text = "Male", Value = "M" };
                genderList.Add(item1);
                SelectListItem item2 = new SelectListItem { Text = "Female", Value = "F" };
                genderList.Add(item2);
                ViewBag.GenderList = genderList;
            }
            return View(patientData);
        }

        // GET: PatientData/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PatientData patientData = db.PatientDatas.Find(id);
            if (patientData == null)
            {
                return HttpNotFound();
            }
            return View(patientData);
        }

        // POST: PatientData/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            PatientData patientData = db.PatientDatas.Find(id);
            db.PatientDatas.Remove(patientData);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult SearchPatientData()
        {
            string lastName = Request.QueryString["ln"];
            string firstName = Request.QueryString["fn"];

            if (lastName.Length > 0 && firstName.Length == 0)
            {
                return View(db.PatientDatas.Where(p => p.Lastname.ToUpper().Contains(lastName.ToUpper())).ToList());
            }

            if (lastName.Length == 0 && firstName.Length > 0)
            {
                return View(db.PatientDatas.Where(p => p.Firstname.ToUpper().Contains(firstName.ToUpper())).ToList());
            }


            return View(db.PatientDatas.Where(p => p.Lastname.ToUpper().Contains(lastName.ToUpper()) || p.Firstname.ToUpper().Contains(firstName.ToUpper())).ToList());

        } //--


        public bool checkPatientExamIdExist(string patient_id)
        {
            bool exist = false;

            string US_ConnStr = ConfigurationManager.ConnectionStrings["USClinic_ADO"].ConnectionString; ;
            using (SqlConnection sqlCon = new SqlConnection(US_ConnStr))
            {
                SqlCommand sqlCmd = new SqlCommand();
                sqlCmd.CommandText = "select * from PatientData Where Patient_Id = @patient_id";
                sqlCmd.Parameters.AddWithValue("@patient_id", patient_id);

                sqlCmd.Connection = sqlCon;
                sqlCon.Open();

                SqlDataReader rdrPdata = sqlCmd.ExecuteReader();
                if (rdrPdata.HasRows)
                { exist = true; }
                else { exist = false; }

            }

            return exist;

        } //--

    }
}

JEVEGA_UsDiagnosticClinic/Views/PatientData/Create.cshtml
@model JEVEGA_UsDiagnosticClinic.PatientData
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/Layout_inner_page.cshtml";
}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script>
    $(document).ready(function ()
    {
        $("input").focus(function () {
            $(this).css("background-color", "aliceblue");
        });

        $("input").blur(function () {
            $(this).css("background-color", "white");
        });

        $("select").focus(function () {
            $(this).css("background-color", "aliceblue");
        });

        $("select").blur(function () {
            $(this).css("background-color", "white");
        });

    });
</script>

<table class="table_clinic_pageheader">
    <tr>
        <td><h3>New Patient Data</h3></td>
        <td align="right"></td>
    </tr>
</table>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <table class="table_clinic">
            <tr>
                <td>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Patient_Id, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Patient_Id, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Patient_Id, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </td>
                <td></td>
            </tr>
            <tr>
                <td nowrap="nowrap">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Lastname, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Lastname, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Lastname, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </td>
                <td nowrap="nowrap">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Firstname, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Firstname, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Firstname, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </td>
                <td>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Sex, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.Sex, (List<SelectListItem>)ViewBag.GenderList, "- Select a Gender -", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Sex, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </td>
                <td>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.Status, (SelectList)ViewBag.MaritalStatusList, "- Select a Status -", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </td>
                <td>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <div class="form-group">
                        @Html.LabelFor(model => model.LMP, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.LMP, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.LMP, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </td>
                <td></td>
            </tr>
        </table>


        <div class="line_space"></div>
        <table class="table table-bordered">
            <tr>
                <td>
                    <input type="submit" value="Add Patient Data" class="btn btn-default" />
                    &nbsp;
                    <input type="button" value="Cancel" class="btn btn-default" onclick="@("window.location.href='" + @Url.Action("Index", "PatientData") + "'");" />
                </td>
            </tr>
        </table>

        <br />
        <span class="error_message_ii">@ViewBag.ErrorDuplicatePatientId</span>
        <br />

    </div>
}

JEVEGA_UsDiagnosticClinic/Views/PatientData/Delete.cshtml
@model JEVEGA_Us_Cliniic.PatientData

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/Layout_inner_page.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PatientData</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lastname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lastname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Firstname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Firstname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sex)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sex)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LoginPassword)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoginPassword)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

JEVEGA_UsDiagnosticClinic/Views/PatientData/Details.cshtml
@model JEVEGA_UsDiagnosticClinic.PatientData
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/Layout_inner_page.cshtml";
}

<table class="table_clinic_pageheader">
    <tr>
        <td><h3>Patient Info</h3></td>
        <td align="right"></td>
    </tr>
</table>

<table class="table_clinic table">
    <tr>
        <td nowrap="nowrap">@Html.LabelFor(model => model.Patient_Id, htmlAttributes: new { @class = "" })</td>
        <td colspan="5"><h4>@Html.DisplayFor(model => model.Patient_Id)</h4></td>
    </tr>
    <tr>
        <td><span class="">Fullname</span></td>
        <td colspan="5"><h4>@Html.DisplayFor(model => model.Lastname), @Html.DisplayFor(model => model.Firstname)</h4></td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(model => model.Age)</td>
        <td>@Html.DisplayFor(model => model.Age)</td>
        <td>@Html.DisplayNameFor(model => model.Sex)</td>
        <td>@Html.DisplayFor(model => model.Sex)</td>
        <td>@Html.DisplayNameFor(model => model.Status)</td>
        <td>@Html.DisplayFor(model => model.Status)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(model => model.Address)</td>
        <td colspan="5">@Html.DisplayFor(model => model.Address)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(model => model.Email)</td>
        <td>@Html.DisplayFor(model => model.Email)</td>
        <td>@Html.DisplayNameFor(model => model.Phone)</td>
        <td colspan="3">@Html.DisplayFor(model => model.Phone)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(model => model.LMP)</td>
        <td colspan="5">@Html.DisplayFor(model => model.LMP)</td>
    </tr>
</table>


<div class="line_space"></div>
<table class="table table-bordered">
    <tr>
        <td>
            <input type="button" value="Back To List" class="btn btn-default" onclick="@("window.location.href='" + @Url.Action("Index", "PatientData") + "'");" />
        </td>
    </tr>
</table>

JEVEGA_UsDiagnosticClinic/Views/PatientData/Edit.cshtml
@model JEVEGA_UsDiagnosticClinic.PatientData
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/Layout_inner_page.cshtml";
}

<table class="table_clinic_pageheader">
    <tr>
        <td><h3>Update Patient Info</h3></td>
        <td align="right"></td>
    </tr>
</table>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        <table class="table_clinic">
            <tr>
                <td>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Patient_Id, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Patient_Id, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                            @Html.ValidationMessageFor(model => model.Patient_Id, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </td>
                <td></td>
            </tr>
            <tr>
                <td nowrap="nowrap">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Lastname, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Lastname, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Lastname, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </td>
                <td nowrap="nowrap">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Firstname, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Firstname, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Firstname, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </td>
                <td>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Sex, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.Sex, (List<SelectListItem>)ViewBag.GenderList, "- Select a Gender -", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Sex, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </td>
                <td>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.Status, (SelectList)ViewBag.MaritalStatusList, "- Select a Status -", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </td>
                <td>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <div class="form-group">
                        @Html.LabelFor(model => model.LMP, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.LMP, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.LMP, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </td>
                <td></td>
            </tr>
        </table>

        <div class="line_space"></div>
        <table class="table table-bordered">
            <tr>
                <td>
                    <input type="submit" value="Update" class="btn btn-default" />
                    &nbsp;
                    <input type="button" value="Cancel" class="btn btn-default" onclick="@("window.location.href='" + @Url.Action("Index", "PatientData") + "'");" />
                </td>
            </tr>
        </table>

    </div>
}

JEVEGA_UsDiagnosticClinic/Views/PatientData/Index.cshtml
@model IEnumerable<JEVEGA_UsDiagnosticClinic.PatientData>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout_inner_page.cshtml";
}

<table class="table_clinic_pageheader">
    <tr>
        <td><h3>Patient Data List</h3></td>
        <td align="right">
            @{
                if (Session["USER_TYPE"] == null)
                { Response.Redirect("/Users/Login"); }

                if (Session["USER_TYPE"].ToString() == "1" || Session["USER_TYPE"].ToString() == "2")
                {
                    <a href=@Url.Action("Create", "PatientData")><img src="~/images/add_icon.png" /></a>
                }
            }
            &nbsp;
            <img src="~/images/search_icon.png" class="hand_cursor" data-toggle="collapse" data-target="#collapseSearchDiv" aria-expanded="false" aria-controls="collapseExample" />
            &nbsp;
        </td>
    </tr>
</table>


<div class="div_space20"></div>
@using (Html.BeginForm())
{

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script>

    $(document).ready(function() {

        $("#divLastname").hide();
        $("#divFirstname").hide();

        $("#searchButton").click(function () {

            var lastname = $("#lastname").val();
            var firstname = $("#firstname").val();

            if (lastname.length == 0 && firstname.length == 0) {
                $("#divLastname").show();
                $("#divFirstname").show();
            }
            else {
                window.location.href = "/PatientData/SearchPatientData?ln=" + lastname + "&fn=" + firstname;
            }
        });

    });

    </script>


    <div class="collapse container" id="collapseSearchDiv">

        <div class="search_div">
            <div class="form-group">
                <span class="table_field_value">Last Name: </span>
                <input type="text" class="form-control" id="lastname" name="lastname" />
                <div id="divLastname"><span class="error_message_jquery">* input Last name</span></div>
            </div>
            <div class="form-group">
                <span class="table_field_value">First Name: </span>
                <input type="text" class="form-control" id="firstname" name="firstname" />
                <div id="divFirstname"><span class="error_message_jquery">* input First name</span></div>
            </div>
            <div class="form-group">
                <input type="button" value="Search Patient" id="searchButton" name="searchButton" />
            </div>
        </div>
    </div>
}


<table class="table table-striped">
    <tr>
        @*<th>@Html.DisplayNameFor(model => model.Id)</th>*@
        <th>@Html.DisplayNameFor(model => model.Patient_Id)</th>
        <th>@Html.DisplayNameFor(model => model.Lastname)</th>
        <th>@Html.DisplayNameFor(model => model.Firstname)</th>
        <th>@Html.DisplayNameFor(model => model.Age)</th>
        <th>@Html.DisplayNameFor(model => model.Sex)</th>
        <th>@Html.DisplayNameFor(model => model.Email)</th>
        <th>@Html.DisplayNameFor(model => model.Phone)</th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            @*<td>@Html.DisplayFor(modelItem => item.Id)</td>*@
            <td>@Html.DisplayFor(modelItem => item.Patient_Id)</td>
            <td>@Html.DisplayFor(modelItem => item.Lastname)</td>
            <td>@Html.DisplayFor(modelItem => item.Firstname)</td>
            <td>@Html.DisplayFor(modelItem => item.Age)</td>
            <td>@Html.DisplayFor(modelItem => item.Sex)</td>
            <td>@Html.DisplayFor(modelItem => item.Email)</td>
            <td>@Html.DisplayFor(modelItem => item.Phone)</td>

            @*<td>@Html.DisplayFor(modelItem => item.LoginPassword)</td>*@

            <td>
                @if (Session["USER_TYPE"].ToString() == "1" || Session["USER_TYPE"].ToString() == "2")
                {
                    <a href=@Url.Action("Edit", new { id = item.Patient_Id }) alt="Edit"><img src="~/images/edit_ico.png" /></a>
                }
                - <a href=@Url.Action("Details", new { id = item.Patient_Id }) alt="Details"><img src="~/images/details_ico.png" /></a>
            </td>
        </tr>
    }

</table>