JEVEGA_UsDiagnosticClinic/Controllers/PatientExamController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JEVEGA_UsDiagnosticClinic;

namespace JEVEGA_UsDiagnosticClinic.Controllers
{
    [Authorize]
    public class PatientExamController : Controller
    {
        private JEVEGA_USEntities db = new JEVEGA_USEntities();
        UtilityHelper utHelp = new UtilityHelper();

        // GET: PatientExam
        public ActionResult Index()
        {
            if (Session["USER_TYPE"] == null)
            {
                return RedirectToAction("Login", "Users", new { @ReturnUrl = "/PatientExam/Index" });
            }

            string datelist = "";
            bool nyear = false;
            bool nmonth = false;

            string query_month = Request.QueryString["mo"];
            string query_year = Request.QueryString["yr"];

            int this_month;
            int this_year;
            if (query_month == null)
            {
                DateTime today = DateTime.Now;
                this_month = today.Month;
                this_year = today.Year;
            }
            else
            {
                this_month = Convert.ToInt32(query_month);
                this_year = Convert.ToInt32(query_year);
            }

            List<SelectListItem> listOfYears = new List<SelectListItem>();
            if (this_year == 2019) { nyear = true; } else { nyear = false; }
            SelectListItem item1 = new SelectListItem { Text = "2019", Value = "2019", Selected = nyear };
            listOfYears.Add(item1);

            if (this_year == 2020) { nyear = true; } else { nyear = false; }
            SelectListItem item2 = new SelectListItem { Text = "2020", Value = "2020", Selected = nyear };
            listOfYears.Add(item2);

            if (this_year == 2021) { nyear = true; } else { nyear = false; }
            SelectListItem item3 = new SelectListItem { Text = "2021", Value = "2021", Selected = nyear };
            listOfYears.Add(item3);

            if (this_year == 2022) { nyear = true; } else { nyear = false; }
            SelectListItem item4 = new SelectListItem { Text = "2022", Value = "2022", Selected = nyear };
            listOfYears.Add(item4);

            if (this_year == 2023) { nyear = true; } else { nyear = false; }
            SelectListItem item5 = new SelectListItem { Text = "2023", Value = "2023", Selected = nyear };
            listOfYears.Add(item5);

            ViewBag.YearsList = listOfYears.ToList();
            //...............................................................................................

            List<SelectListItem> listOfMonths = new List<SelectListItem>();

            if (this_month == 1) { nmonth = true; datelist = "January"; } else { nmonth = false; }
            SelectListItem mo1 = new SelectListItem { Text = "January", Value = "1", Selected = nmonth };
            listOfMonths.Add(mo1);

            if (this_month == 2) { nmonth = true; datelist = "February"; } else { nmonth = false; }
            SelectListItem mo2 = new SelectListItem { Text = "February", Value = "2", Selected = nmonth };
            listOfMonths.Add(mo2);

            if (this_month == 3) { nmonth = true; datelist = "March"; } else { nmonth = false; }
            SelectListItem mo3 = new SelectListItem { Text = "March", Value = "3", Selected = nmonth };
            listOfMonths.Add(mo3);

            if (this_month == 4) { nmonth = true; datelist = "April"; } else { nmonth = false; }
            SelectListItem mo4 = new SelectListItem { Text = "April", Value = "4", Selected = nmonth };
            listOfMonths.Add(mo4);

            if (this_month == 5) { nmonth = true; datelist = "May"; } else { nmonth = false; }
            SelectListItem mo5 = new SelectListItem { Text = "May", Value = "5", Selected = nmonth };
            listOfMonths.Add(mo5);

            if (this_month == 6) { nmonth = true; datelist = "June"; } else { nmonth = false; }
            SelectListItem mo6 = new SelectListItem { Text = "June", Value = "6", Selected = nmonth };
            listOfMonths.Add(mo6);

            if (this_month == 7) { nmonth = true; datelist = "July"; } else { nmonth = false; }
            SelectListItem mo7 = new SelectListItem { Text = "July", Value = "7", Selected = nmonth };
            listOfMonths.Add(mo7);

            if (this_month == 8) { nmonth = true; datelist = "August"; } else { nmonth = false; }
            SelectListItem mo8 = new SelectListItem { Text = "August", Value = "8", Selected = nmonth };
            listOfMonths.Add(mo8);

            if (this_month == 9) { nmonth = true; datelist = "September"; } else { nmonth = false; }
            SelectListItem mo9 = new SelectListItem { Text = "September", Value = "9", Selected = nmonth };
            listOfMonths.Add(mo9);

            if (this_month == 10) { nmonth = true; datelist = "October"; } else { nmonth = false; }
            SelectListItem mo10 = new SelectListItem { Text = "October", Value = "10", Selected = nmonth };
            listOfMonths.Add(mo10);

            if (this_month == 11) { nmonth = true; datelist = "November"; } else { nmonth = false; }
            SelectListItem mo11 = new SelectListItem { Text = "November", Value = "11", Selected = nmonth };
            listOfMonths.Add(mo11);

            if (this_month == 12) { nmonth = true; datelist = "December"; } else { nmonth = false; }
            SelectListItem mo12 = new SelectListItem { Text = "December", Value = "12", Selected = nmonth };
            listOfMonths.Add(mo12);

            ViewBag.MonthsList = listOfMonths.ToList();
            ViewBag.DateList = datelist + " " + this_year;
            //...............................................................................................

            List<PatientExam> patientExamList = db.PatientExams.Where(p => p.ExamDate.Value.Month == this_month).ToList();

            //return View(db.PatientExams.ToList());
            return View(patientExamList);

        } //-- 

        [HttpPost]
        public ActionResult Index(FormCollection formCollection)
        {
            string str_year = formCollection["ListOfYears"];
            int this_year = Convert.ToInt32(str_year);
            bool nyear = false;
            string datelist = "";

            List<SelectListItem> listOfYears = new List<SelectListItem>();
            if (this_year == 2019) { nyear = true; } else { nyear = false; }
            SelectListItem item1 = new SelectListItem { Text = "2019", Value = "2019", Selected = nyear };
            listOfYears.Add(item1);

            if (this_year == 2020) { nyear = true; } else { nyear = false; }
            SelectListItem item2 = new SelectListItem { Text = "2020", Value = "2020", Selected = nyear };
            listOfYears.Add(item2);

            if (this_year == 2021) { nyear = true; } else { nyear = false; }
            SelectListItem item3 = new SelectListItem { Text = "2021", Value = "2021", Selected = nyear };
            listOfYears.Add(item3);

            if (this_year == 2022) { nyear = true; } else { nyear = false; }
            SelectListItem item4 = new SelectListItem { Text = "2022", Value = "2022", Selected = nyear };
            listOfYears.Add(item4);

            if (this_year == 2023) { nyear = true; } else { nyear = false; }
            SelectListItem item5 = new SelectListItem { Text = "2023", Value = "2023", Selected = nyear };
            listOfYears.Add(item5);

            ViewBag.YearsList = listOfYears.ToList();
            //...............................................................................................
            string str_month = formCollection["ListOfMonths"];
            int this_month = Convert.ToInt32(str_month);
            bool nmonth = false;

            List<SelectListItem> listOfMonths = new List<SelectListItem>();

            if (this_month == 1) { nmonth = true; datelist = "January"; } else { nmonth = false; }
            SelectListItem mo1 = new SelectListItem { Text = "January", Value = "1", Selected = nmonth };
            listOfMonths.Add(mo1);

            if (this_month == 2) { nmonth = true; datelist = "February"; } else { nmonth = false; }
            SelectListItem mo2 = new SelectListItem { Text = "February", Value = "2", Selected = nmonth };
            listOfMonths.Add(mo2);

            if (this_month == 3) { nmonth = true; datelist = "March"; } else { nmonth = false; }
            SelectListItem mo3 = new SelectListItem { Text = "March", Value = "3", Selected = nmonth };
            listOfMonths.Add(mo3);

            if (this_month == 4) { nmonth = true; datelist = "April"; } else { nmonth = false; }
            SelectListItem mo4 = new SelectListItem { Text = "April", Value = "4", Selected = nmonth };
            listOfMonths.Add(mo4);

            if (this_month == 5) { nmonth = true; datelist = "May"; } else { nmonth = false; }
            SelectListItem mo5 = new SelectListItem { Text = "May", Value = "5", Selected = nmonth };
            listOfMonths.Add(mo5);

            if (this_month == 6) { nmonth = true; datelist = "June"; } else { nmonth = false; }
            SelectListItem mo6 = new SelectListItem { Text = "June", Value = "6", Selected = nmonth };
            listOfMonths.Add(mo6);

            if (this_month == 7) { nmonth = true; datelist = "July"; } else { nmonth = false; }
            SelectListItem mo7 = new SelectListItem { Text = "July", Value = "7", Selected = nmonth };
            listOfMonths.Add(mo7);

            if (this_month == 8) { nmonth = true; datelist = "August"; } else { nmonth = false; }
            SelectListItem mo8 = new SelectListItem { Text = "August", Value = "8", Selected = nmonth };
            listOfMonths.Add(mo8);

JEVEGA_UsDiagnosticClinic/Views/PatientExam/Edit.cshtml
@model JEVEGA_UsDiagnosticClinic.PatientExam

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/Layout_inner_page.cshtml";
}

<table class="table_clinic_pageheader">
<tr>
    <td><h3>Update Patient Exam Details</h3></td>
    <td align="right"></td>
</tr>
</table>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">

    <hr />
    <table class="table_clinic">
        <tr>
            <td>
                <div class="form-group">
                    @Html.LabelFor(model => model.ExamDate, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ExamDate, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ExamDate, "", new { @class = "text-danger" })
                    </div>
                </div>
            </td>
            <td></td>
        </tr>

        <tr>
            <td>
                <div class="form-group">
                    @Html.LabelFor(model => model.ExamId, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ExamId, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ExamId, "", new { @class = "text-danger" })
                    </div>
                </div>
            </td>
            <td></td>
        </tr>

        <tr>
            <td>
                <div class="form-group">
                    @Html.LabelFor(model => model.PatientID, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <h4>@Html.DisplayFor(model => model.getPatientIdName)</h4>
                        @Html.HiddenFor(model => model.PatientID)
                    </div>
                </div>
            </td>
            <td nowrap="nowrap">
                <div class="form-group">
                    @Html.LabelFor(model => model.ExamType, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.ExamType, (SelectList)ViewBag.ExamtypeList, "- Select an Exam -", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.ExamType, "", new { @class = "text-danger" })
                    </div>
                </div>
            </td>
        </tr>

        <tr><td colspan="2">@Html.LabelFor(model => model.History, htmlAttributes: new { @class = "control-label" })</td> </tr>
        <tr><td><div class="line_space"></div></td></tr>
        <tr>
            <td colspan="2">
                @Html.TextAreaFor(model => model.History, new { @class = "textarea_report", rows = "3" })
            </td>
        </tr>
        <tr><td><div class="div_space20"></div></td></tr>

        <tr>
            <td>
                <div class="form-group">
                    @Html.LabelFor(model => model.Sonographer, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.Sonographer, (SelectList)ViewBag.SonographerList, "- Assigned Sonographer -", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Sonographer, "", new { @class = "text-danger" })
                    </div>
                </div>
            </td>
            <td>
                <div class="form-group">
                    @Html.LabelFor(model => model.Radiologist, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.Radiologist, (SelectList)ViewBag.DoctorList, "- Assigned Doctor -", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Radiologist, "", new { @class = "text-danger" })
                    </div>
                </div>
            </td>
        </tr>
    </table>

    <div class="line_space"></div>
    <table class="table table-bordered">
    <tr>
        <td>
            <input type="submit" value="Update" class="btn btn-default" />
            &nbsp;
            <input type="button" value="Cancel" class="btn btn-default" onclick="@("window.location.href='" + @Url.Action("Index", "PatientExam", new { mo=ViewBag.EditMonth, yr=ViewBag.EditYear }) + "'");" />
        </td>
    </tr>
    </table>
</div>

}

JEVEGA_UsDiagnosticClinic/Views/PatientExam/Index.cshtml
@model IEnumerable<JEVEGA_UsDiagnosticClinic.PatientExam>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout_inner_page.cshtml";
}

<table class="table_clinic_pageheader">
    <tr>
        <td><h3>Patient Exams List | @ViewBag.DateList</h3></td>
        <td align="right">
            @{
                if (Session["USER_TYPE"].ToString() == "1" || Session["USER_TYPE"].ToString() == "2")
                {
                    <a href=@Url.Action("Create", "PatientExam")><img src="~/images/add_icon.png" /></a>
                }
            }
            &nbsp;
        </td>
    </tr>
</table>
<div class="div_space20"></div>


<table class="table table-striped">
    <tr>
        <th>@Html.DisplayNameFor(model => model.PatientID)</th>
        <th>@Html.DisplayNameFor(model => model.ExamId)</th>
        <th>@Html.DisplayNameFor(model => model.ExamType)</th>
        <th>@Html.DisplayNameFor(model => model.ExamDate)</th>
        @*<th>@Html.DisplayNameFor(model => model.Sonographer)</th>*@
        <th>@Html.DisplayNameFor(model => model.Radiologist)</th>
        <th>Images</th>
        <th>@Html.DisplayNameFor(model => model.SignByDoctor)</th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@Html.DisplayFor(modelItem => item.getPatientName)</td>
            <td>@Html.DisplayFor(modelItem => item.ExamId)</td>
            <td>@Html.DisplayFor(modelItem => item.getExamName)</td>
            <td>@Html.DisplayFor(modelItem => item.ExamDate)</td>
            @*<td>@Html.DisplayFor(modelItem => item.getSonographerName)</td>*@
            <td>@Html.DisplayFor(modelItem => item.getDoctorName)</td>

            <td><span class="text_form_value">@item.IsExamImagesExist()</span></td>

            <td>
                @if (item.SignByDoctor == "Y")
                {<span class="text_form_value_ii">@Html.DisplayFor(modelItem => item.getSignDefinition)</span>}
            else
            { <span class="text_form_value">@Html.DisplayFor(modelItem => item.getSignDefinition)</span>}
            </td>

            <td>
                @if (Session["USER_TYPE"].ToString() == "1" || Session["USER_TYPE"].ToString() == "2")
                {
                    <a href=@Url.Action("Edit", new { id = item.Id }) alt="Edit"><img src="~/images/edit_ico.png" /></a>

                    <a href=@Url.Action("InitialReport", new { id = item.Id }) alt="Edit"><img src="~/images/report_initial.png" /></a>
                }
                - <a href=@Url.Action("Details", new { id = item.Id }) alt="Details"><img src="~/images/details_ico.png" /></a>
                - <a href=@Url.Action("ScanImages", new { id = item.Id }) alt="Details"><img src="~/images/scan_images_icon.png" /></a>
                - <a href=@Url.Action("SignMedicalReport", new { id = item.Id }) alt="Sign Report"><img src="~/images/sign_doc_ico.png" /></a>
            </td>
        </tr>
    }

</table>

@using (Html.BeginForm())
{

    <table class="table table-bordered">
        <tr>
            <td nowrap="nowrap">
                @Html.DropDownList("ListOfMonths", (List<SelectListItem>)ViewBag.MonthsList, "- Select an Month -", new { @class = "form-control" })
            </td>
            <td>
                @Html.DropDownList("ListOfYears", (List<SelectListItem>)ViewBag.YearsList, "- Select a Year -", new { @class = "form-control" })
            </td>
            <td>
                <input type="submit" value="Filter by Month/Year" class="btn btn-default" />
            </td>
        </tr>
    </table>


    <div class="div_space20"></div>


}

JEVEGA_UsDiagnosticClinic/Views/PatientExam/PrintExamReport.cshtml
@model JEVEGA_UsDiagnosticClinic.PatientExam

@{
    ViewBag.Title = "PrintExamReport";
    Layout = "~/Views/Shared/Layout_inner_page.cshtml";
}


@using (Html.BeginForm(null, null, FormMethod.Post, new { @action = @Url.Action("PrintReportWithLogo\\" + Model.Id, "PatientExam"), target = "_blank" }))
{
    @Html.AntiForgeryToken()

    <div>
        <div style="float:right">
            <span class="report_text2">Report Date : @Html.DisplayFor(model => model.formattedExamDate)</span>
        </div>

        <div class="div_space20"></div>
        <table class="table-bordered table_clinic">
            <tr>
                <td style="width:140px;"><span class="report_text1" style="padding:7px;">Patient Name:</span></td>
                <td colspan="2"><span class="report_text1">@Html.DisplayFor(model => model.getPatientName)</span></td>
                <td style="width:140px;">
                    <div style="padding:7px;"><span class="report_text1">Exam Id:</span></div>
                </td>
                <td><span class="report_text1">@Html.DisplayFor(model => model.ExamId)</span></td>
            </tr>

            <tr>
                <td><div style="padding:7px;"><span class="print_label">Sex:</span></div></td>
                <td><span class="print_value">@ViewBag.PatientSex</span></td>
                <td><span class="print_label" style="padding:7px;">Age:&nbsp;&nbsp;@ViewBag.Age</span></td>
                <td><span class="print_label" style="padding:7px;">Marital Status:</span></td>
                <td><span class="print_value">@ViewBag.Status</span></td>
            </tr>
        </table>

        <div class="div_space20"></div>
        <div><span class="report_text1">History</span></div>
        <div class="line_space"></div>
        <div class="line_space"></div>

        <table class="table-bordered table_clinic">
            <tr>
                <td style="vertical-align:top;">
                    <div class="div_textarea">
                        <textarea class="textarea_exam_history" readonly >@Html.DisplayFor(model => model.History)</textarea>
                    </div>
                </td>
            </tr>
        </table>

        <div class="div_space20"></div>
        <div><span class="report_text1">Exam : @Html.DisplayFor(model => model.getExamName)</span></div>
        <div class="line_space"></div>
        <div class="line_space"></div>

        <table class="table-bordered table_clinic" style="height:120px;">
            <tr>
                <td style="vertical-align:top;">
                    <div class="div_textarea">
                        <textarea class="textarea_exam_report" readonly >@ViewBag.ExamReport</textarea>
                    </div>
                </td>
            </tr>
        </table>

        <div class="div_space20"></div>
        <div class="div_space20"></div>
        <div class="div_space20"></div>
        <div class="div_space20"></div>

        <div>
            <table class="table_clinic">
                <tr>
                    <td><img src="~/ClinicStaff/sign-1.jpg" style="width:200px;" /></td>
                </tr>
                <tr><td><div class="line_space"></div></td></tr>
                <tr>
                    <td>
                        <span class="report_text2">Report by: Dr. @Html.DisplayFor(model => model.getDoctorFistLastName) - @Html.DisplayFor(model => model.getDoctorPostTitle)</span><br />
                        <span class="report_text2">PRC License No. : @Html.DisplayFor(model => model.getDoctorPRCLicenseNo)</span>
                    </td>
                </tr>
            </table>
        </div>


        <div class="div_space20"></div>
        <div class="div_space20"></div>
        <div class="line_space"></div>
        <table class="table table-bordered">
            <tr>
                <td>
                    <input type="submit" value="Print Using Template" class="btn btn-default" />
                    &nbsp;
                    <input type="button" value="Print In LetterHead" class="btn btn-default" onclick="@("window.location.href='" + @Url.Action("PrintReportLetterHead", "PatientExam") + "'");" />
                    &nbsp;
                    <input type="button" value="Send to OB Doctor" class="btn btn-default" onclick="@("window.location.href='" + @Url.Action("SendExamReportToOBDoctor\\" + Model.Id, "PatientExam") + "'");" />
                    &nbsp;
                    <input type="button" value="Send to Patient" class="btn btn-default" onclick="@("window.location.href='" + @Url.Action("SendExamReportToPatient\\" + Model.Id, "PatientExam") + "'");" />
                </td>
            </tr>
        </table>

    </div>

    }

JEVEGA_UsDiagnosticClinic/Views/PatientExam/SearchPatientExam.cshtml
@{
    ViewBag.Title = "SearchPatientExam";
    Layout = "~/Views/Shared/Layout_inner_page.cshtml";
}

<h2>SearchPatientExam</h2>

JEVEGA_UsDiagnosticClinic/Views/PatientExam/SendExamReportToOBDoctor.cshtml
@{
    ViewBag.Title = "SendExamReportToOBDoctor";
    Layout = "~/Views/Shared/Layout_inner_page.cshtml";
}

<h3>Official Report sent to OB Doctor</h3>

<div class="div_space20"></div>

<span class="error_message">@ViewBag.ResponseMessage</span>

<div class="div_space20"></div>

JEVEGA_UsDiagnosticClinic/Views/PatientExam/SendExamReportToPatient.cshtml
@{
    ViewBag.Title = "SendExamReportToPatient";
    Layout = "~/Views/Shared/Layout_inner_page.cshtml";
}

<h3>Send to Patient's eMail - Diagnostic Official Report</h3>

@if (!ViewBag.Posted)
{
    <hr />
    using (Html.BeginForm())
    {
        <input type="hidden" id="mail_rad_doctor" name="mail_patient" value="@ViewBag.PatientEmail" />
        
        <div>
            <textarea id="mail_subject" name="mail_subject" class="textarea_report" rows="1">@ViewBag.MailSubject</textarea>
        </div>

        <div class="div_space20"></div>

        <div>
            <textarea id="mail_body" name="mail_body" class="textarea_report" rows="14">@ViewBag.MailBody</textarea>
        </div>

        <div class="div_space20"></div>

        <div style="float:right">
            <input type="submit" value="Send Mail" class="btn btn-default" />
            &nbsp;
            <input type="button" value="Cancel" class="btn btn-default" onclick="@("window.location.href='" + @Url.Action("Details/" + ViewBag.PatientExamId, "PatientExam") + "'");" />
        </div>

        <div class="div_space20"></div>
        <div class="div_space20"></div>
    }
}

<span class="error_message">@ViewBag.ResponseMessage</span>
<div class="div_space20"></div>

JEVEGA_UsDiagnosticClinic/Views/PatientExam/SendExamToRadiologist.cshtml
@{
    ViewBag.Title = "SendExamToRadiologist";
    Layout = "~/Views/Shared/Layout_inner_page.cshtml";
}

<h3>Send Mail Notification to Radiologist</h3>

@if (!ViewBag.Posted)
{
  <hr />
  using (Html.BeginForm())
  {
    <input type="hidden" id="mail_rad_doctor" name="mail_rad_doctor" value="@ViewBag.RadDoctorEmail" />

    <div>
        <textarea id="mail_subject" name="mail_subject" class="textarea_report" rows="1">@ViewBag.MailSubject</textarea>
    </div>

    <div class="div_space20"></div>

    <div>
        <textarea id="mail_body" name="mail_body" class="textarea_report" rows="14">@ViewBag.MailBody</textarea>
    </div>

    <div class="div_space20"></div>

    <div style="float:right">
        <input type="submit" value="Send Mail" class="btn btn-default" />
        &nbsp;
        <input type="button" value="Cancel" class="btn btn-default" onclick="@("window.location.href='" + @Url.Action("Details/" + ViewBag.PatientExamId, "PatientExam") + "'");" />
    </div>

    <div class="div_space20"></div>
    <div class="div_space20"></div>
  }
}

<span class="error_message">@ViewBag.ResponseMessage</span>
<div class="div_space20"></div>

JEVEGA_UsDiagnosticClinic/Views/PatientExam/UploadMultipleFiles.cshtml
@model JEVEGA_UsDiagnosticClinic.PatientExam

@{
    ViewBag.Title = "UploadMultipleFiles";
    Layout = "~/Views/Shared/Layout_inner_page.cshtml";
}

<table class="table_clinic_pageheader">
    <tr>
        <td><h3>Scan Images for @ViewBag.PatientName - @ViewBag.PatientExamName on @ViewBag.PatientExamDate | Exam Id: @ViewBag.PatientExamId</h3></td>
        <td align="right"></td>
    </tr>
</table>


@using (Html.BeginForm("UploadMultipleExamImages", "PatientExam", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <input type="hidden" name="patientExamId" id="patientExamId" value="@ViewBag.patientExamEntityKey" />
        <input type="hidden" name="patiendIDNo" id="patiendIDNo" value="@ViewBag.patiendIDNo" />
        <input type="hidden" name="patientExamIdNo" id="patientExamIdNo" value="@ViewBag.PatientExamId" />

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <table class="table_clinic">
        <tr>
            <td>
                <table class="table">
                    <tr><td><span class="table_field_value">Upload Multiple Exam Images</span> </td></tr>

                    <tr><td><input type="file" name="file_exams" id="file_exams" multiple onchange="updateFileList()" /></td></tr>
                </table>
            </td>
        </tr>
        </table>

        <div id="fileList"> .... </div>

        <div class="line_space"></div>
        <table class="table table-bordered">
            <tr>
                <td>
                    <input type="submit" id="submitButton" name="submitButton" value="Upload Scan Images" class="btn btn-default" />
                    &nbsp;
                    <input type="button" value="Cancel" class="btn btn-default" onclick="@("window.location.href='" + @Url.Action("Index", "PatientExam", new { mo=ViewBag.EditMonth, yr=ViewBag.EditYear }) + "'");" />
                </td>
            </tr>
        </table>
    </div>

    <div id="divError" name="divError">
        <br />
        <span class="error_message_ii">Some image files are not valid!  Please select file images again.</span>
        <br />
    </div>
}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script>

    $(document).ready(function ()
    {
        $("#divError").hide();
        $("#submitButton").prop("disabled", true);
    });

    function updateFileList()
    {
        var input = document.getElementById('file_exams');
        var output = document.getElementById('fileList');
        var isImageFileValid;

        isImageFileValid = true;
        output.innerHTML = '<ul>';
        for (var i = 0; i < input.files.length; ++i)
        {
            var inputFilename = input.files.item(i).name;
            if (inputFilename.indexOf(".JPG") == -1 && inputFilename.indexOf(".jpg") == -1) {
                isImageFileValid = false;
            }

            output.innerHTML += '<li>' + input.files.item(i).name + '</li>';
        }
        output.innerHTML += '</ul>';


        if (isImageFileValid) {
            $("#submitButton").prop("disabled", false);
            $("#divError").hide();
        }
        else
        {
            $("#submitButton").prop("disabled", true);
            $("#divError").show();
        }

    }


</script>